services:
  neo4j:
    image: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc","apoc-extended"]
  neodash:
    image: neo4jlabs/neodash
    ports:
      - 5005:5005
volumes:
  neo4j-data:
    name: neo4j-data
